<?php
/**
 * Flexslider : Carrusel Responsivo
 * Esto es un SNIPPET para incluir dentro de una plantilla de página de WP
 * Las imagenes se colocan en la carpeta "images" del directorio del ChildTheme
 * 
 * Javascript:
<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.flexslider').flexslider({
          animation: "slide",
          controlsContainer: ".flex-container"
    });
  });
</script>

*
* Opciones:
namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
animation: "fade",              //String: Select your animation type, "fade" or "slide"
easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
direction: "horizontal",        //String: Select the sliding direction, "horizontal" or "vertical"
reverse: false,                 //{NEW} Boolean: Reverse the animation direction
animationLoop: true,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
smoothHeight: false,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode
startAt: 0,                     //Integer: The slide that the slider should start on. Array notation (0 = first slide)
slideshow: true,                //Boolean: Animate slider automatically
slideshowSpeed: 7000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
animationSpeed: 600,            //Integer: Set the speed of animations, in milliseconds
initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
randomize: false,               //Boolean: Randomize slide order
 
// Usability features
pauseOnAction: true,            //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
pauseOnHover: false,            //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
useCSS: true,                   //{NEW} Boolean: Slider will use CSS3 transitions if available
touch: true,                    //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
video: false,                   //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
 
// Primary Controls
controlNav: true,               //Boolean: Create navigation for paging control of each slide? Note: Leave true for manualControls usage
directionNav: true,             //Boolean: Create navigation for previous/next navigation? (true/false)
prevText: "Previous",           //String: Set the text for the "previous" directionNav item
nextText: "Next",               //String: Set the text for the "next" directionNav item
 
// Secondary Navigation
keyboard: true,                 //Boolean: Allow slider navigating via keyboard left/right keys
multipleKeyboard: false,        //{NEW} Boolean: Allow keyboard navigation to affect multiple sliders. Default behavior cuts out keyboard navigation with more than one slider present.
mousewheel: false,              //{UPDATED} Boolean: Requires jquery.mousewheel.js (https://github.com/brandonaaron/jquery-mousewheel) - Allows slider navigating via mousewheel
pausePlay: false,               //Boolean: Create pause/play dynamic element
pauseText: 'Pause',             //String: Set the text for the "pause" pausePlay item
playText: 'Play',               //String: Set the text for the "play" pausePlay item
 
// Special properties
controlsContainer: "",          //{UPDATED} Selector: USE CLASS SELECTOR. Declare which container the navigation elements should be appended too. Default container is the FlexSlider element. Example use would be ".flexslider-container". Property is ignored if given element is not found.
manualControls: "",             //Selector: Declare custom control navigation. Examples would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
sync: "",                       //{NEW} Selector: Mirror the actions performed on this slider with another slider. Use with care.
asNavFor: "",                   //{NEW} Selector: Internal property exposed for turning the slider into a thumbnail navigation for another slider
 
// Carousel Options
itemWidth: 0,                   //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
itemMargin: 0,                  //{NEW} Integer: Margin between carousel items.
minItems: 0,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
maxItems: 0,                    //{NEW} Integer: Maxmimum number of carousel items that should be visible. Items will resize fluidly when above this limit.
move: 0,                        //{NEW} Integer: Number of carousel items that should move on animation. If 0, slider will move all visible items.
 
// Callback API
start: function(){},            //Callback: function(slider) - Fires when the slider loads the first slide
before: function(){},           //Callback: function(slider) - Fires asynchronously with each slider animation
after: function(){},            //Callback: function(slider) - Fires after each slider animation completes
end: function(){},              //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
added: function(){},            //{NEW} Callback: function(slider) - Fires after a slide is added
removed: function(){}           //{NEW} Callback: function(slider) - Fires after a slide is removed
*/
?>
<div class="flex-container">
  <div class="flex-controls"></div>
  <div class="flexslider loading">
    <ul class="slides">
      <li>
      	<!-- DIAPOSITIVA num 1 -->
      	<!-- // Elige en que pagina aparece
        < ?php if ( is_home() || is_front_page() ) { -->
        <a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/servicios/' ; ?>" target="_self"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slide1.jpg" alt="<?php if( qtrans_getLanguage() == 'eu' ){?>Ieri enpresak iragazgaitze lanetarako erabateko zerbitzua eskaintzen du premia guztiei erantzunez <?php }else { ?>Ieri ofrece un servicio integral en trabajos de impermeabilizaci&oacute;n para todo tipo de necesidades <?php } ?>" /></a>
        <!-- // qtranslate text multidioma -->
        <?php
			if( qtrans_getLanguage() == 'eu' ){ ?>
    			<p class="flex-caption"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/servicios/' ; ?>" target="_self">Ieri enpresak iragazgaitze lanetarako erabateko zerbitzua eskaintzen du premia guztiei erantzunez &raquo;</a></p>
			<?php }else { ?>
        		<p class="flex-caption"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/servicios/' ; ?>" target="_self">Ieri ofrece un servicio integral en trabajos de impermeabilizaci&oacute;n para todo tipo de necesidades &raquo;</a></p>
			<?php } ?>
        <!--}?> -->
      	</li>
       <li>
       	<!-- DIAPOSITIVA num 2 -->
      	<!-- // Elige en que pagina aparece
        < ?php if ( is_home() || is_front_page() ) { -->
        <a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/empresa/' ; ?>" target="_self"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slide2.jpg" alt="<?php if( qtrans_getLanguage() == 'eu' ){?>Ieri iragazgaiketan espezializatutako enpresa bat da, 20 urte baino gehiagoko eskarmentua duena <?php }else { ?>Ieri es una empresa especializada en la impermeabilizaci&oacute;n con m&aacute;s de 20 a&ntilde;os de experiencia en el sector <?php } ?>" /></a>
        <!-- // qtranslate text multidioma -->
        <?php
			if( qtrans_getLanguage() == 'eu' ){ ?>
    			<p class="flex-caption"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/empresa/' ; ?>" target="_self">Ieri iragazgaiketan espezializatutako enpresa bat da, 20 urte baino gehiagoko eskarmentua duena &raquo;</a></p>
			<?php }else { ?>
        		<p class="flex-caption"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/empresa/' ; ?>" target="_self">Ieri es una empresa especializada en la impermeabilizaci&oacute;n con m&aacute;s de 20 a&ntilde;os de experiencia en el sector &raquo;</a></p>
			<?php } ?>
        <!--}?> -->
      </li>
      <li>
      	<!-- DIAPOSITIVA num 3 -->
      	<!-- // Elige en que pagina aparece
        < ?php if ( is_home() || is_front_page() ) { -->
        <a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/contacto/' ; ?>" target="_self"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/slide3.jpg" alt="<?php if( qtrans_getLanguage() == 'eu' ){?>Ez izan zalantzarik iragazgaitzeari buruzko edozein egitasmo guri kontsultatzeko <?php }else { ?>No dude en consultarnos sobre cualquier proyecto relacionado con la impermeabilizaci&oacute;n <?php } ?>" /></a>
        <!-- // qtranslate text multidioma -->
        <?php
			if( qtrans_getLanguage() == 'eu' ){ ?>
    			<p class="flex-caption"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/contacto/' ; ?>" target="_self">Ez izan zalantzarik iragazgaitzeari buruzko edozein egitasmo guri kontsultatzeko &raquo;</a></p>
			<?php }else { ?>
        		<p class="flex-caption"><a href="<?php echo get_bloginfo('url') . ('/') . qtrans_getLanguage() . '/contacto/' ; ?>" target="_self">No dude en consultarnos sobre cualquier proyecto relacionado con la impermeabilizaci&oacute;n &raquo;</a></p>
			<?php } ?>
        <!--}?> -->
      </li>
    </ul>
  </div>
</div>